# Site settings
title: Welcome to Knight9z's GitPages!
description: This GitPages is first set for my final exam.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Welcome To My GitPages!
user_description: Thank you for coming in~~
user_title: Welcome To My GitPages!
email: bble54@163.com
# twitter_username: TBD
# github_username:  rascaaaaal
# gplus_username:  TBD

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
